BEGIN;


CREATE TABLE category (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    label TEXT NOT NULL UNIQUE,
    route TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ 
    );

CREATE TABLE post (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL UNIQUE,
    content TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    category_name text NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ 
    );

ALTER TABLE post ADD CONSTRAINT fk_category_name FOREIGN KEY (category_name) REFERENCES category (label);

COMMIT;