BEGIN;

INSERT INTO instructions VALUES(1,'Serve with rice, you can add coriander');
INSERT INTO instructions VALUES(2,'Once chicken is fried , lower the heat and pour coconut milk , add another tablespoon of curry powder, adjust seasoning and simmer 10 min on low heat');
INSERT INTO instructions VALUES(3,'Add the chicken , 1 tablespoon of curry powder and season with salt and black pepper');
INSERT INTO instructions VALUES(4,'Heat some sesame oil or other oil and onions, saute for 2 or 3 min then add peppers and garlic, stir for 5 or 7 min');
INSERT INTO instructions VALUES(5,'Prepare all ingredients, cut peppers into medium strips, mince the garlic, chop onions into strip, cut chicken into medium pieces');
INSERT INTO instructions VALUES(10,'Serve with rice, you can add coriander');
INSERT INTO instructions VALUES(11,'Once chicken is fried , lower the heat and pour coconut milk , add another tablespoon of curry powder, adjust seasoning and simmer 10 min on low heat');
INSERT INTO instructions VALUES(12,'Add the chicken , 1 tablespoon of curry powder and season with salt and black pepper');
INSERT INTO instructions VALUES(13,'Heat some sesame oil or other oil and onions, saute for 2 or 3 min then add peppers and garlic, stir for 5 or 7 min');
INSERT INTO instructions VALUES(14,'Prepare all ingredients, cut peppers into medium strips, mince the garlic, chop onions into strip, cut chicken into medium pieces');
INSERT INTO instructions VALUES(15,'Serve with rice, you can add coriander');
INSERT INTO instructions VALUES(16,'Once chicken is fried , lower the heat and pour coconut milk , add another tablespoon of curry powder, adjust seasoning and simmer 10 min on low heat');
INSERT INTO instructions VALUES(17,'Add the chicken , 1 tablespoon of curry powder and season with salt and black pepper');
INSERT INTO instructions VALUES(18,'Heat some sesame oil or other oil and onions, saute for 2 or 3 min then add peppers and garlic, stir for 5 or 7 min');
INSERT INTO instructions VALUES(19,'Prepare all ingredients, cut peppers into medium strips, mince the garlic, chop onions into strip, cut chicken into medium pieces');
INSERT INTO instructions VALUES(20,'Serve with rice, you can add coriander');
INSERT INTO instructions VALUES(21,'Once chicken is fried , lower the heat and pour coconut milk , add another tablespoon of curry powder, adjust seasoning and simmer 10 min on low heat');
INSERT INTO instructions VALUES(22,'Add the chicken , 1 tablespoon of curry powder and season with salt and black pepper');
INSERT INTO instructions VALUES(23,'Heat some sesame oil or other oil and onions, saute for 2 or 3 min then add peppers and garlic, stir for 5 or 7 min');
INSERT INTO instructions VALUES(24,'Prepare all ingredients, cut peppers into medium strips, mince the garlic, chop onions into strip, cut chicken into medium pieces');
INSERT INTO instructions VALUES(47,'Serve with rice, you can add coriander');
INSERT INTO instructions VALUES(48,'Once chicken is fried , lower the heat and pour coconut milk , add another tablespoon of curry powder, adjust seasoning and simmer 10 min on low heat');
INSERT INTO instructions VALUES(49,'Add the chicken , 1 tablespoon of curry powder and season with salt and black pepper');
INSERT INTO instructions VALUES(50,'Heat some sesame oil or other oil and onions, saute for 2 or 3 min then add peppers and garlic, stir for 5 or 7 min');
INSERT INTO instructions VALUES(51,'Prepare all ingredients, cut peppers into medium strips, mince the garlic, chop onions into strip, cut chicken into medium pieces');
INSERT INTO instructions VALUES(60,'Serve with rice, you can add coriander ');
INSERT INTO instructions VALUES(61,'Once chicken is fried , lower the heat and pour coconut milk , add another tablespoon of curry powder, adjust seasoning and simmer 10 min on low heat');
INSERT INTO instructions VALUES(62,'Add the chicken , 1 tablespoon of curry powder and season with salt and black pepper');
INSERT INTO instructions VALUES(63,'Heat some sesame oil or other oil and onions, saute for 2 or 3 min then add peppers and garlic, stir for 5 or 7 min');
INSERT INTO instructions VALUES(64,'Prepare all ingredients, cut peppers into medium strips, mince the garlic, chop onions into strip, cut chicken into medium pieces');
INSERT INTO instructions VALUES(65, 'Pour the dressing over the salad, making sure to coat it evenly. Serve immediately!');

INSERT INTO instructions VALUES(66,'Add the quartered hard-boiled eggs');
INSERT INTO instructions VALUES(67,'Add the sliced cooked chicken to the salad');
INSERT INTO instructions VALUES(68,'Add the sliced tomatoes, croutons, and grated Parmesan cheese to the lettuce.');
INSERT INTO instructions VALUES(69,'In a large salad bowl, place the torn lettuce leaves');
INSERT INTO instructions VALUES(70,'Start by preparing the dressing. In a small bowl, whisk together soya sauce, red wine vinegar, mustard, greek yogurt, honey .Slowly add the olive oil while whisking constantly to emulsify the dressing. Season with black peper and cumin to taste. Set aside.');
INSERT INTO instructions VALUES(71,'Cook the chicken breast over high heat');
INSERT INTO instructions VALUES(72,'Start by boiling 9 to 11min the eggs until they are hard-boiled ');
INSERT INTO instructions VALUES(73, 'Pour the pasta into the pan with the pork bellys (with the heat turned off), then quickly add the egg and Parmesan mixture, stirring well. Be careful not to let the eggs cook too quickly, or you might end up with scrambled eggs! Gradually add a little pasta cooking water until you achieve a creamy sauce consistency. It''s ready! Serve immediately with some Parmesan cheese shavings on top.');
INSERT INTO instructions VALUES(74, 'Towards the end of the pasta cooking time, gently reheat the pork bellys over low heat. Drain the pasta, reserving a small amount of the cooking water in a separate bowl.');
INSERT INTO instructions VALUES(75,'In a bowl, mix the egg, egg yolks, and grated Parmesan cheese. Season generously with freshly ground pepper.');
INSERT INTO instructions VALUES(76,'After 2-3 minutes over high heat, remove most of the fat from the pan, leaving about one tablespoon. Set aside.');
INSERT INTO instructions VALUES(77, 'Meanwhile, cut the porrk bellys into thick 1cm-sided lardons. Grill the pancetta in a pan without adding any fat.');
INSERT INTO instructions VALUES(78,'Add the pasta to the boiling water and cooked them aldente');
INSERT INTO instructions VALUES(79,'Bring a large pot of water to a boil. No need to add salt, as the pork and parmesan cheese should be salty enough.');
INSERT INTO instructions VALUES(80, 'Taste and adjust the seasoning with salt and pepper if needed. Serve the chicken Basquaise hot with rice, garnished with fresh chopped parsley.');
INSERT INTO instructions VALUES(81,'Reduce the heat to low, cover the skillet, and simmer for about 30-40 minutes, or until the chicken is cooked through and tender.');
INSERT INTO instructions VALUES(82,'Return the chicken pieces to the skillet, nestling them into the vegetable mixture.');
INSERT INTO instructions VALUES(83,'Pour in the chicken broth and white wine, and stir to combine.');
INSERT INTO instructions VALUES(84,'Stir in thepeeled, seeded and chopped tomatoes, espelette pepper and dried oregano. Cook for a few minutes to allow the flavors to meld together.');
INSERT INTO instructions VALUES(85,'Add the sliced peppers to the skillet and cook until they start to soften.');
INSERT INTO instructions VALUES(86,'In the same skillet, add the sliced onion and minced garlic. Sauté until the onion becomes translucent.');
INSERT INTO instructions VALUES(87,'In a large skillet or Dutch oven, heat the olive oil over medium-high heat.');
INSERT INTO instructions VALUES(88,'Season the chicken pieces with salt and pepper.');
INSERT INTO instructions VALUES(89,'Serve the couscous accompanied by semolina, meat, merguez sausages, vegetables, and broth.');
INSERT INTO instructions VALUES(90,'Grill the merguez sausages in a dry skillet.');
INSERT INTO instructions VALUES(91,'Cook semolina by soaking it in one and a half times its volume of water. Fluff it with the butter cut into small pieces.');
INSERT INTO instructions VALUES(92,'Cover with enough water to submerge the ingredients and bring to a simmer. Let it simmer for 1 hour covered.');
INSERT INTO instructions VALUES(93,'Add the peeled and chopped carrots, the peeled and quartered turnips, and the drained chickpeas. Add the tomato paste, ras el hanout, harissa, and a pinch of salt. Return the onions and crushed garlic to the pan.');
INSERT INTO instructions VALUES(94,'In a sauté pan, heat the olive oil. Sauté the onions until golden brown, remove them and place the lamb and chicken in the pan. Sauté for a few minutes.');
INSERT INTO instructions VALUES(95,'Cut the lamb neck into large cubes.');
INSERT INTO instructions VALUES(96,'Serve over buttered white rice and garnish with fresh green onions and sesame seeds.');
INSERT INTO instructions VALUES(97,'Return the chicken to the pan and mix well.');
INSERT INTO instructions VALUES(98,'Bring to a boil while stirring constantly until the sauce thickens.');
INSERT INTO instructions VALUES(99,'Pour the marinade into the pan, add the butter, and return to medium heat.');
INSERT INTO instructions VALUES(100,'Remove the pan from the heat (to prevent the bottom from burning and giving a bitter taste) and transfer the chicken in Teriyaki sauce to a bowl.');
INSERT INTO instructions VALUES(101,'Cook the chicken in the pan until the pieces turn a beautiful golden color, stirring occasionally.');
INSERT INTO instructions VALUES(102,'Remove the chicken pieces from the marinade using a slotted spoon.');
INSERT INTO instructions VALUES(103,'Heat a large non-stick pan and add 1 tablespoon of olive oil.');
INSERT INTO instructions VALUES(104,'In a bowl, mix together the soya sauce, honey, orange juice, ginger, and sesame oil.');
INSERT INTO instructions VALUES(105,'Cut the chicken escalopes into small cubes after rinsing them.');
INSERT INTO instructions VALUES(106,'Transfer the Cantonese rice to a shallow dish. Arrange the chicken strips on top and drizzle with their cooking juices. Sprinkle with chopped parsley and serve immediately.');
INSERT INTO instructions VALUES(107,'Fluff the rice with a fork. Heat the peanut oil in a sauté pan or wok. Add the rice and spring onions. Sauté them over high heat for 5 minutes, stirring. Then add the pieces of ham, peas, and diced omelette. Mix well and continue cooking for 3 minutes.');
INSERT INTO instructions VALUES(108,'Heat a non-stick frying pan and cook the omelette in it. Remove it from the pan and cut it into small cubes.');
INSERT INTO instructions VALUES(109,'Meanwhile, cut the slices of ham into small cubes. Slice the spring onions. Beat the eggs with the remaining sesame oil and a pinch of salt.');
INSERT INTO instructions VALUES(110,'Heat 3 tablespoons of sesame oil in a pan and brown the chicken strips in it. When they are well browned, season with salt and pepper and pour in the lemon juice. Bring to a boil, then let it simmer for 20 minutes over low heat.');
INSERT INTO instructions VALUES(111,'On the same day, cut the chicken breasts into strips. Squeeze the lemons. Wash, dry, and finely chop the parsley.');
INSERT INTO instructions VALUES(112,'The day before, cook the rice in boiling salted water for the time indicated on the package. Drain it and, after cooling, refrigerate it covered with plastic wrap.');
INSERT INTO instructions VALUES(113,'Serve with rice');
INSERT INTO instructions VALUES(114, 'Dissolve the beef bouillon powder in 240ml of hot water, then add it to the pot. Reduce the heat to low and let the chili simmer for about 30-40 minutes, allowing the flavors to meld together.');
INSERT INTO instructions VALUES(115, 'Pour in the tomato puree and stir to incorporate it into the mixture. Season with salt and pepper according to your taste.');
INSERT INTO instructions VALUES(116,'Pour in the tomato puree and stir to incorporate it into the mixture.');
INSERT INTO instructions VALUES(117,'Sprinkle the chili powder, cumin, and garlic powder over the meat and vegetable mixture. Stir to evenly coat everything with the spices.');
INSERT INTO instructions VALUES(118,'Once the beef is cooked, add the diced bell peppers and corn kernels to the pot. Stir well to combine.');
INSERT INTO instructions VALUES(119,'Add the ground beef to the pot and cook until browned, breaking it up into crumbles with a spatula');
INSERT INTO instructions VALUES(120, 'Heat a drizzle of olive oil in a large pot or Dutch oven over medium heat. Add the chopped red onion and minced garlic to the pot. Sauté until the onion becomes translucent and fragrant.');
INSERT INTO instructions VALUES(121,'Prepare the dressing by mixing olive oil, balsamic vinegar, greek yogurt and mustard in a bowl. Add salt and pepper to taste.');
INSERT INTO instructions VALUES(122,'Add sliced mozarella to the bowl');
INSERT INTO instructions VALUES(123, 'Cook the chicken in a pan for approximately 10 minutes. Once the chicken breasts are cooked, let them cool, then slice them and add them to the salad bowl.');
INSERT INTO instructions VALUES(124,'Cook your eggs in a pot of boiling water for 9 minutes until hard-boiled, then let them cool , slice them in quarter and add them to the bowl');
INSERT INTO instructions VALUES(125,'Peel and grate your cucumber, then add it to the salad bowl.');
INSERT INTO instructions VALUES(126,'Wash and halve your cherry tomatoes, then add them sliced in two to the salad bowl ');
INSERT INTO instructions VALUES(127,'Wash and dry your salad greens, then place them in a salad bowl (you can use any type of green lettuce, romaine, arugula, etc.).');
INSERT INTO instructions VALUES(128,'Now add the marinated chicken and marinade to the wok and stir-fry for 5 minutes, mixing well until the chicken is cooked. You can either toast the cashews separately in a pan or add them directly to the wok. Remove from heat as soon as they are nicely browned,  and serve immediately with rice');
INSERT INTO instructions VALUES(129,'In a wok or large frying pan, heat the peanut oil or sesame oil and stir-fry the espelette pepper, black pepper with minced garlic, ginger, onion, and red pepper.');
INSERT INTO instructions VALUES(130,'Add the chicken to the marinade, mix well, and let it marinate in the refrigerator for at least 30 minutes.');
INSERT INTO instructions VALUES(131,'Prepare the marinade by mixing soy sauce, rice vinegar, granulated sugar, and cornstarch in a bowl. If the marinade is too thick, add a little soy sauce.');
INSERT INTO instructions VALUES(132,'Cook your pasta the serve hot');
INSERT INTO instructions VALUES(133,'Add roughly chopped tomatoes, tomatoes puree, mixed herbs and vegetables , reduce heat and simmer covered for 1 to 1h30 hours, allowing the wine to evaporate.');
INSERT INTO instructions VALUES(134,'Add the broth, red wine and tomatoes concentrate, let reduce');
INSERT INTO instructions VALUES(135,'In a other pan, add the ground beef. Brown it and stir to prevent the meat from forming large clumps.');
INSERT INTO instructions VALUES(136,'Heat the oil in a large enough saucepan. Sauté the garlic, chopped onion and cutted carrot over low heat for 5 minutes, stirring.');
INSERT INTO instructions VALUES(137,'Reduce the heat , then add fresh cream, mustard, oregano and some cooking water from pasta, then add pasta and serve !');
INSERT INTO instructions VALUES(138,'In another non-stick pan, brown the diced chicken breasts .Then add them to the mushroom mixture along with salt and pepper, and let it cook for 6 to 8 minutes.');
INSERT INTO instructions VALUES(139, 'Pour the chicken broth and white wine over the mixture and let it cook for another 10 minutes. Meanwhile cook the pasta, keep cooking water.');
INSERT INTO instructions VALUES(140,'Then add the mushrooms and continue cooking for another 2 minutes, stirring.');
INSERT INTO instructions VALUES(141,'sauté the chopped shallots, minced garlic in a pan with olive oil for 3 minutes, stirring without browning them.');
INSERT INTO instructions VALUES(142, 'Add chicken and his marinade to the vegetables. Reduce the heat for few minutes. Serve with rice!');
INSERT INTO instructions VALUES(143, 'Add yellow pepper and zucchini to eggplants. In another pan, cook the marinade until the chicken is golden.');
INSERT INTO instructions VALUES(144,'In a heat pan , add sliced eggplants and cook them for few minutes.');
INSERT INTO instructions VALUES(145,'In a bowl add chopped chicken , soy sauce, espelette pepper , salt, black pepper and any spices you like. Stir');

SELECT setval('instructions_id_seq',(SELECT MAX(id) FROM instructions), true);
COMMIT;